export const celebrities = [
  {
    name: 'Leonardo',
    surname: 'DiCaprio',
    phone: '5551234567',
    email: 'leo@hollywood.com',
    address: 'Beverly Hills, CA',
    job: 'Actor',
  },
  {
    name: 'Taylor',
    surname: 'Swift',
    phone: '5552345678',
    email: 'taylor@swift.com',
    address: 'Nashville, TN',
    job: 'Singer',
  },
  {
    name: 'Cristiano',
    surname: 'Ronaldo',
    phone: '5553456789',
    email: 'cr7@football.com',
    address: 'Riyadh, Saudi Arabia',
    job: 'Footballer',
  },
  {
    name: 'Emma',
    surname: 'Watson',
    phone: '5554567890',
    email: 'emma@watson.com',
    address: 'London, UK',
    job: 'Actress',
  },
  {
    name: 'Elon',
    surname: 'Musk',
    phone: '5555678901',
    email: 'elon@tesla.com',
    address: 'Austin, TX',
    job: 'CEO',
  },
  {
    name: 'Angelina',
    surname: 'Jolie',
    phone: '5556789012',
    email: 'angelina@jolie.com',
    address: 'Los Angeles, CA',
    job: 'Actress',
  },
  {
    name: 'Brad',
    surname: 'Pitt',
    phone: '5557890123',
    email: 'brad@pitt.com',
    address: 'Los Angeles, CA',
    job: 'Actor',
  },
  {
    name: 'Beyoncé',
    surname: 'Knowles',
    phone: '5558901234',
    email: 'beyonce@music.com',
    address: 'Houston, TX',
    job: 'Singer',
  },
  {
    name: 'Tom',
    surname: 'Cruise',
    phone: '5559012345',
    email: 'tom@cruise.com',
    address: 'Los Angeles, CA',
    job: 'Actor',
  },
  {
    name: 'Jennifer',
    surname: 'Lawrence',
    phone: '5550123456',
    email: 'jennifer@lawrence.com',
    address: 'Louisville, KY',
    job: 'Actress',
  },
  {
    name: 'Robert',
    surname: 'Downey Jr.',
    phone: '5551122334',
    email: 'robert@stark.com',
    address: 'New York, NY',
    job: 'Actor',
  },
  {
    name: 'Scarlett',
    surname: 'Johansson',
    phone: '5552233445',
    email: 'scarlett@marvel.com',
    address: 'New York, NY',
    job: 'Actress',
  },
  {
    name: 'Johnny',
    surname: 'Depp',
    phone: '5553344556',
    email: 'johnny@depp.com',
    address: 'Los Angeles, CA',
    job: 'Actor',
  },
  {
    name: 'Lady',
    surname: 'Gaga',
    phone: '5554455667',
    email: 'lady@gaga.com',
    address: 'New York, NY',
    job: 'Singer',
  },
  {
    name: 'Will',
    surname: 'Smith',
    phone: '5555566778',
    email: 'will@smith.com',
    address: 'Philadelphia, PA',
    job: 'Actor',
  },
];
